export enum Step {
  Trosak = 'Trošak poslodavca',
  Ukupno = 'Ukupna plaća',
  Neoporezivo = 'Neoporezivo',
  Bruto1 = 'Bruto 1',
  TreciStup = 'Treći stup',
  Neto = 'Neto',
  NeoporeziviDodaci = 'Neoporezivi dodaci',
  NaRacun = 'Na račun',
  PoreziPrirezi = 'Porezi/prirezi',
  Oporezivo = 'Porezna osnovica',
  OsobniOdbitak = 'Osobni odbitak',
  Drzava = 'Država',
  Doprinosi = 'Doprinosi',
  BrutoDoprinosi = 'Doprinosi na bruto plaću',
  Porez = 'Porez',
  Prirez = 'Prirez',
}
