import { Step } from '../enums/Step';

export const chart = [
  (state: any) => [
    ['Iz', 'U', 'Iznos'],
    [Step.Ukupno, Step.Neoporezivo, state.neoporezivo],
    [Step.Neoporezivo, Step.TreciStup, state.treciStup],
    [Step.Neoporezivo, Step.NaRacun, state.neoporezivo - state.treciStup],
    [Step.Ukupno, Step.Bruto1, state.bruto1],
    [Step.Neto, Step.NaRacun, state.neto],
    [Step.Bruto1, Step.Drzava, state.porezi + state.doprinosi],
    [Step.Bruto1, Step.Neto, parseFloat((state.odbitakCalc + state.oporezivo - state.porezi).toFixed(2))],
  ],
  (state: any) => [
    ['Iz', 'U', 'Iznos'],
    [Step.Ukupno, Step.Neoporezivo, state.neoporezivo],
    [Step.Neoporezivo, Step.TreciStup, state.treciStup],
    [Step.Neoporezivo, Step.NeoporeziviDodaci, state.neoporezivo - state.treciStup],
    [Step.NeoporeziviDodaci, Step.NaRacun, state.neoporezivo - state.treciStup],
    [Step.Ukupno, Step.Bruto1, state.bruto1],
    [Step.Neto, Step.NaRacun, state.neto],
    [Step.Bruto1, Step.Oporezivo, state.oporezivo],
    [Step.Bruto1, Step.OsobniOdbitak, state.odbitakCalc],
    [Step.OsobniOdbitak, Step.Neto, state.odbitakCalc],
    [Step.Oporezivo, Step.Drzava, state.porezi],
    [Step.Bruto1, Step.Doprinosi, state.doprinosi],
    [Step.Doprinosi, Step.Drzava, state.doprinosi],
    [Step.Oporezivo, Step.Neto, parseFloat((state.oporezivo - state.porezi).toFixed(2))],
  ],
  (state: any) => [
    ['Iz', 'U', 'Iznos'],
    [Step.Trosak, Step.Ukupno, state.total],
    [Step.Trosak, Step.BrutoDoprinosi, state.brutoDoprinosi],
    [Step.Ukupno, Step.Neoporezivo, state.neoporezivo],
    [Step.Neoporezivo, Step.TreciStup, state.treciStup],
    [Step.Neoporezivo, Step.NeoporeziviDodaci, state.neoporezivo - state.treciStup],
    [Step.NeoporeziviDodaci, Step.NaRacun, state.neoporezivo - state.treciStup],
    [Step.Ukupno, Step.Bruto1, state.bruto1],
    [Step.Neto, Step.NaRacun, state.neto],
    [Step.Bruto1, Step.Oporezivo, state.oporezivo],
    [Step.Bruto1, Step.OsobniOdbitak, state.odbitakCalc],
    [Step.OsobniOdbitak, Step.Neto, state.odbitakCalc],
    [Step.Oporezivo, Step.Porez, state.porez],
    [Step.Oporezivo, Step.Prirez, state.prirez],
    [Step.Porez, Step.Drzava, state.porez],
    [Step.Prirez, Step.Drzava, state.prirez],
    [Step.Bruto1, Step.Doprinosi, state.doprinosi],
    [Step.Doprinosi, Step.Drzava, state.doprinosi],
    [Step.Oporezivo, Step.Neto, parseFloat((state.oporezivo - state.porezi).toFixed(2))],
    [Step.BrutoDoprinosi, Step.Drzava, state.brutoDoprinosi],
  ],
];

export const fields = [
  ['trosak', 'bruto1', 'neto', 'davanja', 'racun', 'povrat', 'korekcija2021'],
  ['trosak', 'bruto1', 'neto', 'brutoDoprinosi', 'doprinosi', 'porez', 'prirez', 'racun', 'povrat', 'korekcija2021'],
  [
    'trosak',
    'bruto1',
    'neto',
    'brutoDoprinosi',
    'doprinosi',
    'odbitak',
    'odbitakCalc',
    'porez',
    'prirez',
    'racun',
    'povrat',
    'korekcija2021',
  ],
];
